### ISSUE TITLE
Wording on index.md could be improved

### ISSUE THREAD

**Issue by morancj** [OP-TEE/optee_website#118]
Examples:
* "ended up"
* Sentence starting with "But before"
* Sentence ending "etc."
* Sentence starting with "A bit"
* The whole sentence starting with "In 2015"
* Another sentence starting with "But for"

I could attempt a rewrite suggestion in a PR, but I'm not a marketing guru. :smiley:

**Comment by jbech-linaro** [comment]
> I could attempt a rewrite suggestion in a PR, but I'm not a marketing guru.

I wouldn't mind of you change it. This mostly comes from my "Swenglish", so having you as a native speaker will certainly make it better even if you're not a marketing guru :)

**Comment by morancj** [comment]
@jbech-linaro : how about adding @EbbaSimpson into the project? She can then suggest improvements in a PR via edits on GitHub. I'm happy to try and help either way.

**Comment by jbech-linaro** [comment]
That also works, but since this is "our" technical area, it's probably better if we write something up and then let Ebba review it, or?
