### ISSUE TITLE
TA可信应用在ta目录下Makefile文件添加外部libmysqlclient库提示不能添加符号，识别不了格式，这是什么原因？

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_website#125]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.op-tee.org/contact/

**Comment by jbech-linaro** [comment]
? I'm confused?

**Comment by vchong** [comment]
@jiangbinghua 请将问题发送到 https://github.com/OP-TEE/optee_os/issues/new 去。也请使用英语。OP-TEE的维护者都不懂中文。本存储库只用于网站相关问题。此外请参考 https://github.com/OP-TEE/optee_os/issues/3862。谢谢。

**Comment by jforissier** [comment]
@vchong indeed, wǒ bù dǒng zhōngwén ;-) I can hardly decipher a few words in Pinyin, but certainly not ideograms :-/

**Comment by vchong** [comment]
@jforissier Hey, that's pretty good! :+1: I've to use google translate myself. ;)

**Comment by jiangbinghua** [comment]
When TA trusted application adds external libmysqlclient library to makefile file in Ta directory, it indicates that symbols cannot be added and format cannot be recognized. What is the reason? I want to connect TA to MySQL database.
