### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by kylekirkby** [OP-TEE/optee_website#17]
Hi all,
Due to enabling a new LinkChecker on our static site CI builds we have unveiled a few broken links. If anyone can help find the correct replacement for the following link it would be much appreciated:

https://github.com/OP-TEE/optee_website/blob/master/faq/README.md -> https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/drivers/tee?id=refs/tags/next-20170403

Many Thanks,

Kyle

**Comment by shovanuk** [comment]
@jbech-linaro Can you help?
