### ISSUE TITLE
https://www.op-tee.org/<sub page> fails to load

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_website#34]
https://www.op-tee.org/blog/op-tee-qa fails to load ((404 page not found)
https://www.op-tee.org/blog/op-tee-qa/ loads fine
https://www.op-tee.org/blog/op-tee-qa should load too

Thanks!

**Comment by shovanuk** [comment]
@kylekirkby will have a look at it

**Comment by jbech-linaro** [comment]
I've just noticed the exact same issue when trying:
https://www.op-tee.org/security-advisories which gives a 404, hover adding the slash:
https://www.op-tee.org/security-advisories/ and it works fine.

**Comment by vchong** [comment]
Looks like all the sub pages are like that.

https://www.op-tee.org/about/ vs https://www.op-tee.org/about
https://www.op-tee.org/swg/ vs https://www.op-tee.org/swg
https://www.op-tee.org/committee/ vs https://www.op-tee.org/committee
..
the list goes on..

**Comment by shovanuk** [comment]
@vchong @jbech-linaro we are aware of this issue. It to do with our AWS hosting, we are working out best workaround this

**Comment by kylekirkby** [comment]
Hi all,

I just wanted to post an update on this issue. Two of our main sites - linaro.org and 96boards.org - have been switched over to a new AWS setup so this is no longer an issue. OP-TEE will be switched over soon. Sorry for any issues/inconveniences.

Many Thanks,

Kyle

**Comment by pcolmer** [comment]
This is now fixed. Thank you for your patience.
