### ISSUE TITLE
Problem with dependencies/README.md

### ISSUE THREAD

**Issue by kylekirkby** [OP-TEE/optee_website#58]
Does this page need updating? As it does not look like this is a list of the dependencies for running OP-TEE. Looks like a duplicate of this page - https://www.op-tee.org/swg/

Not necessarily urgent just noticed when testing the new top nav for OP-TEE.org

URL:  https://www.op-tee.org/dependencies/

**Comment by jbech-linaro** [comment]
Remove the dependencies page, I have no idea why that is there. At the same time I could see that we still have the "https://www.op-tee.org/committee/", that should also be removed (we don't have any committee).
