### ISSUE TITLE
vxWorks hyperlink is not rendered correctly

### ISSUE THREAD

**Issue by daniel-thompson** [OP-TEE/optee_website#64]
The vxWorks hyperlink is not rendered correctly. I can't really see what is wrong with the markdown but perhaps the converter is being confused by the trademark acknowledgement?

URL:  https://www.op-tee.org/

**Comment by jbech-linaro** [comment]
Agree, markdown looks correct. @kylekirkby, any idea? The ® symbol as Daniel suspect?

**Comment by kylekirkby** [comment]
@jbech-linaro @daniel-thompson My fault, pushing an update through now.
