### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pcolmer** [OP-TEE/optee_website#83]
There are a couple of broken links on the develop branch of the site:

````
2 failed links have been found:
/blog/op-tee-qa/index.html:
    https://www.op-tee.org/about/
/legal/index.html:
    https://www.op-tee.org/about/
````

As a reminder, links to itself should be relative and not absolute.

**Comment by jbech-linaro** [comment]
Thanks @pcolmer . Could you check/fix this @kylekirkby ?

**Comment by kylekirkby** [comment]
Hi @jbech-linaro,

I'll get this synced with master asap :)

Cheers,

Kyle

**Comment by jbech-linaro** [comment]
Thanks @kylekirkby !
